spring:
  datasource:
    url: jdbc:mysql://localhost:3306/total_shakes
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update